# Generated by Django 5.2.8 on 2025-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRunCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('runs', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
